"""empty message

Revision ID: 2b8c9997cf1c
Revises: 999fcfbe3315
Create Date: 2024-03-12 14:50:53.071000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b8c9997cf1c"
down_revision = "999fcfbe3315"
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("email", type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
